workbook:
  template_path: "input_template/"
  output_path: "output/"

system:
  availability: 0.53

sheets:
  System_Availability:
    sheet_name: "System_Availability"         
    year_row: 6
    month_row: 7
    last_row: 18
    start_column : 3
    start_year: 2025
    start_month: 1
    data:
      downtime_sys1:
        row: 10
      downtime_sys2:
        row: 14
      avg_availablitiy:
        row: 18
  Count_Size:
    sheet_name: "Count_Size"         
    year_row: 5
    month_row: 6
    last_row: 11
    start_column : 3
    start_year: 2025
    start_month: 1
    data:
      document_count:
        row: 7
      tenant_count:
        row: 8
      storage:
        row: 11 
  Dashboard:
    sheet_name: "Dashboard"
    start_column: 3    # Column C
    end_column: 14     # Column N
    report_period:
      start_row: 6
      start_col: 2     
      end_row: 6
      end_col: 3       
    table1:
      start_row: 11    # First row of table 1
      end_row: 15      # Last row of table 1
      year_row: 11     # Row with year
      month_row: 12    # Row with month labels
      formula_rows:    # Rows where formulas need to be shifted by 1 column
        - 13
        - 14
        - 15
    table2:
      start_row: 18   # First row of table 2
      end_row: 21      # Last row of table 2
      year_row: 18     # Row with year
      month_row: 19    # Row with month labels
      formula_rows:    # Rows where formulas need to be shifted by 1 column
        - 20
        - 21
